import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

import localFont from '@next/font/local'


const swiss = localFont({
    src: [{
        path:'../public/swiss911.otf',
        weight:"200"
    }],
    variable: '--font-swiss',

})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <div
          style={{ backgroundImage: `url("/jeopardy.jpeg")` }}
          className="flex flex-col h-screen w-screen  bg-cover "

      >
        <main className={`flex flex-col flex-1 ${swiss.variable} font-sans-serif`}>{children}</main>
      </div>
      </body>
    </html>
  )
}
