import {Question} from "@/shared/types/Game.types";

export const jeopardyQuestions: Question[] = [
    {
        text: "This term refers to a potential customer that has shown interest in your product or service.",
        answer: "lead",
        value: 200,
        numAttempts: 0,
        numCorrect: 0,
        category: "Sales",
    },
    {
        text: "The stage in the sales process where a salesperson meets with a prospect to explore their needs and preferences.",
        answer: "discovery",
        value: 400,
        numAttempts: 0,
        numCorrect: 0,
        category: "Sales",
    },
    {
        text: "This sales technique involves making an unsolicited contact with potential customers to introduce your product or service.",
        answer: "cold calling",
        value: 600,
        numAttempts: 0,
        numCorrect: 0,
        category: "Sales",
    },
    {
        text: "This metric represents the average time it takes for a sales representative to respond to a lead's inquiry.",
        answer: "lead response time",
        value: 800,
        numAttempts: 0,
        numCorrect: 0,
        category: "Sales",
    },
    {
        text: "The process of guiding a prospect through the sales funnel towards making a purchase.",
        answer: "sales pipeline",
        value: 1000,
        numAttempts: 0,
        numCorrect: 0,
        category: "Sales",
    },
    {
        text: "This sales approach focuses on building long-term relationships with customers to ensure repeat business.",
        answer: "relationship selling",
        value: 1200,
        numAttempts: 0,
        numCorrect: 0,
        category: "Sales",
    },
    {
        text: "In sales, this term refers to a customer who has left positive feedback and is likely to recommend your product or service to others.",
        answer: "promoter",
        value: 1600,
        numAttempts: 0,
        numCorrect: 0,
        category: "Sales",
    },
    {
        text: "This is a technique used to overcome objections and persuade a prospect to make a purchase.",
        answer: "objection handling",
        value: 2000,
        numAttempts: 0,
        numCorrect: 0,
        category: "Sales",
    },

    // Category: Marketing
    {
        text: "This marketing technique involves persuading customers to share their experiences and opinions about a product or service.",
        answer: "word-of-mouth marketing",
        value: 200,
        numAttempts: 0,
        numCorrect: 0,
        category: "Marketing",
    },
    {
        text: "The process of dividing a market into distinct groups based on characteristics and behaviors.",
        answer: "market segmentation",
        value: 400,
        numAttempts: 0,
        numCorrect: 0,
        category: "Marketing",
    },
    {
        text: "This marketing strategy involves setting low prices to attract customers and gain market share.",
        answer: "penetration pricing",
        value: 600,
        numAttempts: 0,
        numCorrect: 0,
        category: "Marketing",
    },
    {
        text: "The unique blend of product, place, price, and promotion that a company uses to attract customers.",
        answer: "marketing mix",
        value: 800,
        numAttempts: 0,
        numCorrect: 0,
        category: "Marketing",
    },
    {
        text: "This digital marketing channel focuses on improving a website's visibility in search engine results.",
        answer: "search engine optimization (SEO)",
        value: 1000,
        numAttempts: 0,
        numCorrect: 0,
        category: "Marketing",
    },
    {
        text: "In marketing, this term refers to the group of people a company aims to reach with its products or services.",
        answer: "target audience",
        value: 1200,
        numAttempts: 0,
        numCorrect: 0,
        category: "Marketing",
    },
    {
        text: "This marketing metric measures the average number of times a person sees an advertisement.",
        answer: "ad impressions",
        value: 1600,
        numAttempts: 0,
        numCorrect: 0,
        category: "Marketing",
    },
    {
        text: "The process of creating and sharing valuable content to attract and engage a target audience.",
        answer: "content marketing",
        value: 2000,
        numAttempts: 0,
        numCorrect: 0,
        category: "Marketing",
    },

    // Category: Customer Success
    {
        text: "This is a metric that measures the percentage of customers who remain subscribed to your service over a given period.",
        answer: "customer retention rate",
        value: 200,
        numAttempts: 0,
        numCorrect: 0,
        category: "Customer Success",
    },
    {
        text: "In customer success, this term refers to the process of helping customers get maximum value from a product or service.",
        answer: "onboarding",
        value: 400,
        numAttempts: 0,
        numCorrect: 0,
        category: "Customer Success",
    },
    {
        text: "The stage in the customer journey where a customer decides whether to continue using a product or service.",
        answer: "adoption phase",
        value: 600,
        numAttempts: 0,
        numCorrect: 0,
        category: "Customer Success",
    },
    {
        text: "This customer success strategy involves reaching out to customers to gather feedback and identify areas for improvement.",
        answer: "customer feedback loop",
        value: 800,
        numAttempts: 0,
        numCorrect: 0,
        category: "Customer Success",
    },
    {
        text: "In customer success, this term refers to customers who actively promote and advocate for your brand.",
        answer: "brand ambassadors",
        value: 1000,
        numAttempts: 0,
        numCorrect: 0,
        category: "Customer Success",
    },
    {
        text: "The process of proactively addressing customer issues and challenges to prevent churn.",
        answer: "proactive customer support",
        value: 1200,
        numAttempts: 0,
        numCorrect: 0,
        category: "Customer Success",
    },
    {
        text: "This customer success metric measures the total revenue generated by a single customer over their lifetime.",
        answer: "customer lifetime value (CLV)",
        value: 1600,
        numAttempts: 0,
        numCorrect: 0,
        category: "Customer Success",
    },
    {
        text: "In customer success, this term refers to the process of helping customers achieve their specific goals using your product or service.",
        answer: "customer outcomes",
        value: 2000,
        numAttempts: 0,
        numCorrect: 0,
        category: "Customer Success",
    },

    // Category: Finance
    {
        text: "This financial statement provides a snapshot of a company's financial position at a specific point in time.",
        answer: "balance sheet",
        value: 200,
        numAttempts: 0,
        numCorrect: 0,
        category: "Finance",
    },
    {
        text: "The process of recording financial transactions and events in a systematic manner.",
        answer: "bookkeeping",
        value: 400,
        numAttempts: 0,
        numCorrect: 0,
        category: "Finance",
    },
    {
        text: "This financial metric measures a company's ability to meet its short-term obligations with its current assets.",
        answer: "current ratio",
        value: 600,
        numAttempts: 0,
        numCorrect: 0,
        category: "Finance",
    },
    {
        text: "The cost of borrowing money, usually expressed as an annual percentage.",
        answer: "interest rate",
        value: 800,
        numAttempts: 0,
        numCorrect: 0,
        category: "Finance",
    },
    {
        text: "This financial analysis technique compares a company's financial performance to industry peers.",
        answer: "benchmarking",
        value: 1000,
        numAttempts: 0,
        numCorrect: 0,
        category: "Finance",
    },
    {
        text: "The total amount of money that a company earns before deducting expenses.",
        answer: "revenue",
        value: 1200,
        numAttempts: 0,
        numCorrect: 0,
        category: "Finance",
    },
    {
        text: "This financial statement shows a company's revenues and expenses over a specific period.",
        answer: "income statement",
        value: 1600,
        numAttempts: 0,
        numCorrect: 0,
        category: "Finance",
    },
    {
        text: "The process of estimating the future financial performance of a company.",
        answer: "financial forecasting",
        value: 2000,
        numAttempts: 0,
        numCorrect: 0,
        category: "Finance",
    },

    // Category: Data Analysis
    {
        text: "This type of analysis is used to discover patterns and relationships in large datasets.",
        answer: "data mining",
        value: 200,
        numAttempts: 0,
        numCorrect: 0,
        category: "Data Analysis",
    },
    {
        text: "The process of cleaning and organizing data to make it suitable for analysis.",
        answer: "data preprocessing",
        value: 400,
        numAttempts: 0,
        numCorrect: 0,
        category: "Data Analysis",
    },
    {
        text: "This statistical measure represents the average of a set of values.",
        answer: "mean",
        value: 600,
        numAttempts: 0,
        numCorrect: 0,
        category: "Data Analysis",
    },
    {
        text: "The process of visually representing data to identify patterns and trends.",
        answer: "data visualization",
        value: 800,
        numAttempts: 0,
        numCorrect: 0,
        category: "Data Analysis",
    },
    {
        text: "This data analysis method is used to make predictions based on historical data.",
        answer: "predictive modeling",
        value: 1000,
        numAttempts: 0,
        numCorrect: 0,
        category: "Data Analysis",
    },
    {
        text: "A data analysis technique that measures the strength and direction of the relationship between two variables.",
        answer: "correlation analysis",
        value: 1200,
        numAttempts: 0,
        numCorrect: 0,
        category: "Data Analysis",
    },
    {
        text: "This data analysis tool is widely used for spreadsheets and data manipulation.",
        answer: "Microsoft Excel",
        value: 1600,
        numAttempts: 0,
        numCorrect: 0,
        category: "Data Analysis",
    },
    {
        text: "The process of extracting useful information from unstructured data sources like text documents or social media posts.",
        answer: "text mining",
        value: 2000,
        numAttempts: 0,
        numCorrect: 0,
        category: "Data Analysis",
    },
    {
        text: "This sales technique involves making personalized recommendations based on a customer's needs and preferences.",
        answer: "consultative selling",
        value: 400,
        numAttempts: 0,
        numCorrect: 0,
        category: "Sales",
    },
    {
        text: "The process of following up with customers after a purchase to ensure their satisfaction and address any issues.",
        answer: "post-sales support",
        value: 800,
        numAttempts: 0,
        numCorrect: 0,
        category: "Sales",
    },

    // Category: Marketing (Continued)
    {
        text: "This marketing metric measures the percentage of visitors who take a desired action on a website.",
        answer: "conversion rate",
        value: 400,
        numAttempts: 0,
        numCorrect: 0,
        category: "Marketing",
    },
    {
        text: "The process of creating a distinctive name and image for a product or service in the minds of customers.",
        answer: "branding",
        value: 800,
        numAttempts: 0,
        numCorrect: 0,
        category: "Marketing",
    },

    // Category: Customer Success (Continued)
    {
        text: "This customer success strategy involves identifying and reaching out to customers who are at risk of churning.",
        answer: "churn prevention",
        value: 400,
        numAttempts: 0,
        numCorrect: 0,
        category: "Customer Success",
    },
    {
        text: "The process of encouraging customers to upgrade to a higher-tier product or service.",
        answer: "upselling",
        value: 800,
        numAttempts: 0,
        numCorrect: 0,
        category: "Customer Success",
    },

    // Category: Finance (Continued)
    {
        text: "This financial metric measures a company's efficiency in using its assets to generate revenue.",
        answer: "asset turnover ratio",
        value: 400,
        numAttempts: 0,
        numCorrect: 0,
        category: "Finance",
    },
    {
        text: "The process of forecasting future financial performance based on historical data and external factors.",
        answer: "financial modeling",
        value: 800,
        numAttempts: 0,
        numCorrect: 0,
        category: "Finance",
    },

    // Category: Data Analysis (Continued)
    {
        text: "This statistical measure represents the middle value in a dataset.",
        answer: "median",
        value: 400,
        numAttempts: 0,
        numCorrect: 0,
        category: "Data Analysis",
    },
    {
        text: "The process of identifying and correcting errors or inconsistencies in a dataset.",
        answer: "data cleansing",
        value: 800,
        numAttempts: 0,
        numCorrect: 0,
        category: "Data Analysis",
    },
];

